{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "64376649",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyvcf\n",
      "  Downloading PyVCF-0.6.8.tar.gz (34 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_a5483256b1a3477fb7359a7a43984edc/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_a5483256b1a3477fb7359a7a43984edc/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-hp30x43l\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_a5483256b1a3477fb7359a7a43984edc/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/20/b6/36bfb1760f6983788d916096193fc14c83cce512c7787c93380e09458c09/PyVCF-0.6.8.tar.gz#sha256=e9d872513d179d229ab61da47a33f42726e9613784d1cb2bac3f8e2642f6f9d9 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.7.tar.gz (31 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_f5c913efaca14b3c9366470db101e8f5/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_f5c913efaca14b3c9366470db101e8f5/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-7xef2g5p\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_f5c913efaca14b3c9366470db101e8f5/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/64/1b/7c393d0cd5b1de2bb025d6ef45f71a013258214ae3564ede54adbd74ad00/PyVCF-0.6.7.tar.gz#sha256=998361f824f828f689e8e1043f795403c11e561d719cc85cdd17c3679fa9b4aa (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.6.tar.gz (30 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_b19427f0a21a49c39c8a51b2c25f2e26/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_b19427f0a21a49c39c8a51b2c25f2e26/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-yuqf4trn\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_b19427f0a21a49c39c8a51b2c25f2e26/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f7/b5/0c1763caa7502b71b43ef486211230fb6bfe30568b01594859150d5b2339/PyVCF-0.6.6.tar.gz#sha256=d0517b0ebd41a4064aa4cc6545617597d84ef7772c96713c170f39b68a997186 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.5.tar.gz (30 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_39d1e8c016f34f3a94446b26e6507132/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_39d1e8c016f34f3a94446b26e6507132/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-qceb58j2\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_39d1e8c016f34f3a94446b26e6507132/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/10/a7/f97d71cf4b0a22a2adc55564b3dab6bf1a90ef6592ad2db0c5b8a58c5e0a/PyVCF-0.6.5.tar.gz#sha256=458b012fe69842acd49d87913f1eb068696c01b03aea7c04d6b8e14f13872c13 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.4.tar.gz (29 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_1fe27322a6e14674866f25e2b2ee0179/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_1fe27322a6e14674866f25e2b2ee0179/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-td8g8dpe\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_1fe27322a6e14674866f25e2b2ee0179/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/30/db/fd30981c363499c9b51687b7d06e891937c3136073b5771b2e30c0453aae/PyVCF-0.6.4.tar.gz#sha256=10aef49ed2a4de7a64d51d92dd30441d350b24619f328d879cbd86611031b18a (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.3.tar.gz (27 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_3cb655e8380a40d58de95d2939afbf0e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_3cb655e8380a40d58de95d2939afbf0e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-ypf0tlnx\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_3cb655e8380a40d58de95d2939afbf0e/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/38/3a/a3b7a9b36cd2d8aedbe1335887c50441b942cb3e990def4b327f1ee21147/PyVCF-0.6.3.tar.gz#sha256=44b6f753472b2f9b2c5e3f08959d1f6532076fcf83223f3797256ac7b8ede60d (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading PyVCF-0.6.2.tar.gz (26 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_d375851fe8034290bd75469ebc57c446/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_d375851fe8034290bd75469ebc57c446/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-uajgrv9e\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_d375851fe8034290bd75469ebc57c446/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/4b/2bbb1ee971de3d6b516ba4dc152027488fe6f15fc396620881750a9b51d0/PyVCF-0.6.2.tar.gz#sha256=aebd8dc67ea92d307976ae73ed0add8d9e1b6c7e09343decfa960e0e597f28b1 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.1.tar.gz (26 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ce385fd54c4078b962122da9ce1ec7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ce385fd54c4078b962122da9ce1ec7/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-ohcg06yi\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ce385fd54c4078b962122da9ce1ec7/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6f/49/e46405959069b27ee605f7646e7ec7d5c220e981a11fa8a76f28bb5dee17/PyVCF-0.6.1.tar.gz#sha256=41e0369cc7852011f4fb277e2b5282439715d6edde2ee9cdde0e1262e78b2389 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.6.0.tar.gz (27 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_13d139ee531241c29a3a1b39823571f4/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_13d139ee531241c29a3a1b39823571f4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-m6g1twn8\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_13d139ee531241c29a3a1b39823571f4/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4e/ae/b43f6a7dca99957ebee1d0944213a6a1490595e04aa4ad95fb25c69dbcd9/PyVCF-0.6.0.tar.gz#sha256=d9ec3bbedb64fa35c2648a9c41fdefaedd3912ff597a436e073d27aeccf5de7c (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.5.0.tar.gz (23 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_6c76972daa1841fca1a1daafc869a806/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_6c76972daa1841fca1a1daafc869a806/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-qnx2etpa\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_6c76972daa1841fca1a1daafc869a806/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/db/4c/b2c4f3f1eba4913dc531e0b5d27a1219f3edd767007f1a02f753207e1647/PyVCF-0.5.0.tar.gz#sha256=51cc9ffea4f1e9ae2095d41abd371afe4581b4c7203094f7647e7a2a071e50c9 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.4.6.tar.gz (19 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ddc49ded374e3f8da8ab30b135216c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ddc49ded374e3f8da8ab30b135216c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-iwpetqua\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_52ddc49ded374e3f8da8ab30b135216c/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ca/25/bfe4a71b1f65d0bcd3e7353c26a35fce513bd8c0f5e1dfce9d42d2f37c27/PyVCF-0.4.6.tar.gz#sha256=6e41ba239b2644664bf4c64a2638ca4870afb144ff5891a1fd37ad2adad79e40 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.4.5.tar.gz (19 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_572586cebc8840f0a17c5d612e17090e/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_572586cebc8840f0a17c5d612e17090e/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-8gg69mq4\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_572586cebc8840f0a17c5d612e17090e/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/8f/c4/e1c71b3e00d2c2a5149933558e088e3a42a27b94620f47f5b2cb861642a8/PyVCF-0.4.5.tar.gz#sha256=4c7367d3a55d7ba8c404241b12cbdf011b5fa7a95034a1c779489523292a2d47 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25h  Downloading PyVCF-0.4.4.tar.gz (19 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/ashikaramesh/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_4e167d736ab1497998dc9b090381da93/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_4e167d736ab1497998dc9b090381da93/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-pip-egg-info-930kkft_\n",
      "       cwd: /private/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/pip-install-fhcyntbp/pyvcf_4e167d736ab1497998dc9b090381da93/\n",
      "  Complete output (1 lines):\n",
      "  error in PyVCF setup command: use_2to3 is invalid.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e3/38/e1b52283c76ef5ef2fc4a5e005bfd308ff14be5483f09b2e5268bd06ae9d/PyVCF-0.4.4.tar.gz#sha256=4576d8a46958fc51a0c100ee0c8aa768e6d8a7fb84706a97a1fbdebd97f49e70 (from https://pypi.org/simple/pyvcf/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading PyVCF-0.4.3.tar.gz (17 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hBuilding wheels for collected packages: pyvcf\n",
      "  Building wheel for pyvcf (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pyvcf: filename=PyVCF-0.4.3-py3-none-any.whl size=16158 sha256=d0ca6fb88d3e6235bad7bbb9ac08065be8ef2f8be3bc23219e77a1cd9f080eef\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/f9/3f/f2/4da50c1e0c57afb2b17589433e794cc9a3b688164a69e3b395\n",
      "Successfully built pyvcf\n",
      "Installing collected packages: pyvcf\n",
      "Successfully installed pyvcf-0.4.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pyvcf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c89571a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting fuc\n",
      "  Downloading fuc-0.30.0-py3-none-any.whl (143 kB)\n",
      "     |████████████████████████████████| 143 kB 4.7 MB/s            \n",
      "\u001b[?25hCollecting biopython\n",
      "  Downloading biopython-1.79-cp39-cp39-macosx_10_9_x86_64.whl (2.3 MB)\n",
      "     |████████████████████████████████| 2.3 MB 4.6 MB/s            \n",
      "\u001b[?25hCollecting pysam\n",
      "  Downloading pysam-0.18.0-cp39-cp39-macosx_10_9_x86_64.whl (3.2 MB)\n",
      "     |████████████████████████████████| 3.2 MB 13.7 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: scipy in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from fuc) (1.8.0)\n",
      "Requirement already satisfied: pandas in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from fuc) (1.4.0)\n",
      "Collecting lxml\n",
      "  Downloading lxml-4.8.0-cp39-cp39-macosx_10_15_x86_64.whl (4.6 MB)\n",
      "     |████████████████████████████████| 4.6 MB 11.2 MB/s            \n",
      "\u001b[?25hCollecting statsmodels\n",
      "  Downloading statsmodels-0.13.2-cp39-cp39-macosx_10_9_x86_64.whl (9.6 MB)\n",
      "     |████████████████████████████████| 9.6 MB 9.0 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: numpy in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from fuc) (1.21.2)\n",
      "Collecting pyranges\n",
      "  Downloading pyranges-0.0.115.tar.gz (685 kB)\n",
      "     |████████████████████████████████| 685 kB 10.7 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting matplotlib-venn\n",
      "  Downloading matplotlib-venn-0.11.6.tar.gz (29 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting seaborn\n",
      "  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)\n",
      "     |████████████████████████████████| 292 kB 12.5 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: matplotlib in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from fuc) (3.5.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (9.0.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (0.11.0)\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (21.3)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (4.29.1)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (2.8.2)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (3.0.6)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from matplotlib->fuc) (1.3.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from pandas->fuc) (2021.3)\n",
      "Collecting cython\n",
      "  Downloading Cython-0.29.28-py2.py3-none-any.whl (983 kB)\n",
      "     |████████████████████████████████| 983 kB 13.5 MB/s            \n",
      "\u001b[?25hCollecting ncls>=0.0.63\n",
      "  Downloading ncls-0.0.64.tar.gz (470 kB)\n",
      "     |████████████████████████████████| 470 kB 12.8 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting tabulate\n",
      "  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)\n",
      "Collecting sorted_nearest>=0.0.33\n",
      "  Downloading sorted_nearest-0.0.33.tar.gz (1.2 MB)\n",
      "     |████████████████████████████████| 1.2 MB 4.5 MB/s            \n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting pyrle\n",
      "  Downloading pyrle-0.0.34.tar.gz (400 kB)\n",
      "     |████████████████████████████████| 400 kB 3.6 MB/s            \n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting natsort\n",
      "  Downloading natsort-8.1.0-py3-none-any.whl (37 kB)\n",
      "Collecting patsy>=0.5.2\n",
      "  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)\n",
      "     |████████████████████████████████| 233 kB 4.7 MB/s            \n",
      "\u001b[?25hRequirement already satisfied: six in /Users/ashikaramesh/miniconda3/lib/python3.9/site-packages (from patsy>=0.5.2->statsmodels->fuc) (1.16.0)\n",
      "Building wheels for collected packages: matplotlib-venn, pyranges, ncls, sorted-nearest, pyrle\n",
      "  Building wheel for matplotlib-venn (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for matplotlib-venn: filename=matplotlib_venn-0.11.6-py3-none-any.whl size=32065 sha256=e9d32f0ed0789032d75f16a139da0d807110ead943821aa71e53a46fc12ceefa\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/42/1c/65/1a733895cd94885d1a97eee84ec7595ff7fddc277a45bcacf5\n",
      "  Building wheel for pyranges (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pyranges: filename=pyranges-0.0.115-py3-none-any.whl size=695217 sha256=34bf31b020359da240c3f9297fbc741d0d493a98afcfdbf670a8f5e9615cb52e\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/c9/a6/ae/97781d804025fab53ad93f469c98424e8406c0fb9680a509a5\n",
      "  Building wheel for ncls (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for ncls: filename=ncls-0.0.64-cp39-cp39-macosx_10_9_x86_64.whl size=819607 sha256=37a250aa78fda846df20d2c515393529fd993336d203931d86cb409a50d8c885\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/1d/d6/36/0cebd25bd9d8e1f6f57e658b7ef2d42557cbfaf1150886337d\n",
      "  Building wheel for sorted-nearest (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for sorted-nearest: filename=sorted_nearest-0.0.33-cp39-cp39-macosx_10_9_x86_64.whl size=2122069 sha256=3b44dda0014ec1581c575c9a5f8faba79e2327a1bc3b616300b51fd00e20b8bb\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/11/33/c7/763348e3a0103c7885251e72beb6dca9d4a8e59de52913c492\n",
      "  Building wheel for pyrle (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pyrle: filename=pyrle-0.0.34-cp39-cp39-macosx_10_9_x86_64.whl size=589205 sha256=06eb3ea9e68abaa949ea06dd83cc6a40de0045f2190263d0fc343d9d7fd25523\n",
      "  Stored in directory: /Users/ashikaramesh/Library/Caches/pip/wheels/be/cd/9f/c013c93620a2d1c102f0d8ca98c93b7276a6d53d3f4a89de6c\n",
      "Successfully built matplotlib-venn pyranges ncls sorted-nearest pyrle\n",
      "Installing collected packages: tabulate, natsort, cython, sorted-nearest, pyrle, patsy, ncls, statsmodels, seaborn, pysam, pyranges, matplotlib-venn, lxml, biopython, fuc\n",
      "Successfully installed biopython-1.79 cython-0.29.28 fuc-0.30.0 lxml-4.8.0 matplotlib-venn-0.11.6 natsort-8.1.0 ncls-0.0.64 patsy-0.5.2 pyranges-0.0.115 pyrle-0.0.34 pysam-0.18.0 seaborn-0.11.2 sorted-nearest-0.0.33 statsmodels-0.13.2 tabulate-0.8.9\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install fuc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4c702633",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fuc import common , pyvcf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "749d7b7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "common.load_dataset('pyvcf')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ea242247",
   "metadata": {},
   "outputs": [],
   "source": [
    "vcf_file = '/Users/ashikaramesh/Documents/LachanceLab/impute/chr_22/chr22.filtered.vcf'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "175dca82",
   "metadata": {},
   "outputs": [],
   "source": [
    "vcf = pyvcf.VcfFrame.from_file(vcf_file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "35f0f175",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'vf' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/1y/wwrznkx94r5cc2z58952bz5w0000gn/T/ipykernel_42435/2763721449.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mvf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplot_hist_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'#AF'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'vf' is not defined"
     ]
    }
   ],
   "source": [
    "vf.plot_hist_info('#AF')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c23e039",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
